# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhujiguanli', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='usertype',
        ),
    ]
