# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhujiguanli', '0002_auto_20161127_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='user_group',
            new_name='usergroup',
        ),
    ]
